server.address=0.0.0.0
spring.application.name=server

spring.data.mongodb.uri=${MONGO_URI}

server.port=${PORT}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

gemini.api.key=${GEMINI_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
